### PR TITLE
suggested errata files

### PR DESCRIPTION
**Pull request by SpudGunMan**
optional include at flash time is easy with old scripts

### CODE REVIEW

**Comment by SpudGunMan** [comment]
I added the original tools updated and back on here to keep up with documentation and quick start

**Review by ste7anste7an — COMMENTED** [review]
This /tools direcotry has nothing to do with the tools in the directory in github.com/antonvh/flash-esp/ . So I think you should do these pull requests in that repository rather than in micropython_ulab_lvgl.

**Review by ste7anste7an — COMMENTED** [review]
Connecting UartRemote to ur=UartRemote(port="/dev/tty.LEGOHubSpikeHub2") wont work I am affraid. It only works on one of the physical ports A-F on the hub. Furthermore, I do not want the ESP32 to start from flash in the ur.loop(), because than people connecting the board for the first time, wont see the Micropython REPL prompt and would think that the module would be broken.

**Comment by SpudGunMan** [comment]
> Connecting UartRemote to ur=UartRemote(port="/dev/tty.LEGOHubSpikeHub2") wont work I am affraid. It only works on one of the physical ports A-F on the hub. Furthermore, I do not want the ESP32 to start from flash in the ur.loop(), because than people connecting the board for the first time, wont see the Micropython REPL prompt and would think that the module would be broken.

yes I missed that wile messing about, it will work on desktopOSX to connect which is fun but dont belong here sorry

**Pull request closed without merging**
